#!/bin/bash

# 


hosts=/etc/hosts
hostsbak=/etc/hosts.update_hosts.bak

if [ $UID != 0 ]; then
    echo "Please run this tool as root."
    exit 1
fi

if [ -f $hosts ]; then
    cp -f $hosts $hostsbak
    sed -i '/^#start_update_hosts.*/,/^#end_update_hosts.*/d' $hosts
else
    touch $hosts
fi

if which dig &>/dev/null; then 
    GOOGLE=`dig @8.8.4.4 g.cn +short | sed -n '$p'`
    #TWITTER=`dig @8.8.4.4 twitter.com +short | sed -n '$p'`
    COMIC178=`dig @202.96.113.34 www.dmzj.com +short | sed -n '$p'`
    WIKI=`dig @8.8.4.4 en.wikipedia.org +short | sed -n '$p'`
    HENTAI=`dig @8.8.4.4 hentaischool.com +short | sed -n '$p'`
    TOPHENTAI=`dig @8.8.4.4 hentai.animestigma.com +short | sed -n '$p'`    
    TAOBAO=`dig @8.8.4.4 www.taobao.com +short | sed -n '$p'` 
    EHENTAI=`dig @8.8.4.4 g.e-hentai.org +short | sed -n '$p'`  
    YZH=`dig @8.8.4.4 yzh.jottit.com +short | sed -n '$p'`
    STAOBAO=`dig @8.8.4.4 s.taobao.com +short | sed -n '$p'` 
    LGTAOBAO=`dig @8.8.4.4 login.taobao.com +short | sed -n '$p'`
    ITMTAOBAO=`dig @8.8.4.4 item.taobao.com +short | sed -n '$p'`    
    TMLTAOBAO=`dig @8.8.4.4 detail.tmall.com +short | sed -n '$p'`       
    BAIDU=`dig @8.8.4.4 www.baidu.com +short | sed -n '$p'`             
     ZHIDAO=`dig @8.8.4.4 zhidao.baidu.com +short | sed -n '$p'`       
     BAIKE=`dig @8.8.4.4 baike.baidu.com +short | sed -n '$p'`       
     ZHWIKI=`dig @8.8.4.4 zh.wikipedia.org +short | sed -n '$p'`       
        MJR=`dig @8.8.4.4 repo.manjaro.org.uk +short | sed -n '$p'`   
     TRANS=`dig @8.8.4.4 translate.google.cn        +short | sed -n '$p'`        
     #SSL=`dig @8.8.4.4 encrypted.google.com +short | sed -n '$p'`    
          MJRCN=`dig @8.8.4.4 mirrors.ustc.edu.cn +short | sed -n '$p'`    
             AUR=`dig @8.8.4.4 aur.archlinux.org +short | sed -n '$p'`    
               ETHERPAD=`dig @8.8.4.4 notes.typo3.org +short | sed -n '$p'`    
              #HJTT=`dig @8.8.4.4 hentai.jottit.com +short | sed -n '$p'`
               ARCHWIKI=`dig @8.8.4.4 wiki.archlinux.org +short | sed -n '$p'`     
               AUTHZFB=`dig @8.8.4.4 auth.alipay.com +short | sed -n '$p'`       
               CSHRZFB=`dig @8.8.4.4 cashier.alipay.com +short | sed -n '$p'`    
             WIKIMJR=`dig @8.8.4.4 wiki.manjaro.org +short | sed -n '$p'`        
        MINUS=`dig @8.8.4.4 yzh123.minus.com +short | sed -n '$p'`        
           OHLOH=`dig @8.8.4.4 www.ohloh.net +short | sed -n '$p'`    
              #FCBK=`dig @8.8.4.4 www.facebook.com +short | sed -n '$p'`    
              RWGTHB=`dig @8.8.4.4 raw.github.com +short | sed -n '$p'`
              GTHB=`dig @8.8.4.4 github.com +short | sed -n '$p'`
             IMGFST=`dig @202.96.113.34 imgfast.dmzj.com +short | sed -n '$p'`
             IMGFSTD=`dig @202.96.113.34 imgfastd.dmzj.com +short | sed -n '$p'`
             GOOGLE2=`dig @8.8.4.4 www.google.cn +short | sed -n '$p'`
         GOOGLE3=`dig @8.8.4.4 google.cn +short | sed -n '$p'`
         WIKIIMG=`dig @8.8.4.4 upload.wikimedia.org +short | sed -n '$p'`
          #EL=`dig @8.8.4.4 piratepad.ca +short | sed -n '$p'`
          #DASHTMLPST=`dig @8.8.4.4 htmlpaste.com +short | sed -n '$p'`
DASNODEUNBLOCKER=`dig @8.8.4.4 node-unblocker.herokuapp.com +short | sed -n '$p'`
#DASGGDV=`dig @8.8.4.4 googledrive.com +short | sed -n '$p'`
DAS=`dig @8.8.4.4 example.org +short | sed -n '$p'`
DAS=`dig @8.8.4.4 example.org +short | sed -n '$p'`
DAS=`dig @8.8.4.4 example.org +short | sed -n '$p'`
    #EL=`dig @8.8.4.4 piratepad.ca +short | sed -n '$p'`
      DASTUDOU=`dig @8.8.4.4 tudou.com +short | sed -n '$p'`
   DASJSTUDOU=`dig @8.8.4.4 js.tudouui.com +short | sed -n '$p'`
else
    echo "Please install dig first."
fi

for ip in "$DASJSTUDOU""$DASTUDOU""$DASHTMLPST""$DASNODEUNBLOCKER""$DASGGDV""$DAS""$EL""WIKIIMG""GOOGLE3""GOOGLE2""$IMGFST""$IMGFSTD""$GTHB""$RWGTHB""$FCBK""$OHLOH""$MINUS""$WKIKMJR""$CSHRZFB""$AUTHZFB""$ARCHWIKI""$HJTT""$ETHERPAD""$AUR""$GOOGLE" "$TWITTER""$COMIC178""$WIKI""$HENTAI""$TOPHENTAI""$XMARKS""$TAOBAO""$EHENTAI""$YZH""$STAOBAO""$LGTAOBAO""$ITMAOBAO""$TMLTAOBAO""$BAIDU""$ZHIDAO""$BAIKE""$ZHWIKI""$MJR""$TRANS""$SSL""$MJRCN"; do
    if [ -z $ip ]; then
        echo "Network unaviable."
        exit 1
    fi
done

cat >>$hosts <<EOF
#start_update_hosts
$GOOGLE3 www.google.dk
$GOOGLE3 www.google.de
$GOOGLE3 www.google.ru
$GOOGLE3 www.google.co.jp

$DASTUDOU tudou.com
$DASJSTUDOU js.tudouui.com


$DASHTMLPST htmlpaste.com
$DASNODEUNBLOCKER node-unblocker.herokuapp.com
$GOOGLE2 googledrive.com
$GOOGLE2 translate.google.dk
$GOOGLE3 translate.google.ru
$GOOGLE translate.google.de

$GOOGLE3 support.google.com
$GOOGLE2 translate.google.ca
$EL piratepad.ca
$GOOGLE translate.google.co.jp
$GOOGLE3 smarthosts.googlecode.com
0.0.0.0 ck.juicyads.com
$WIKIIMG upload.wikimedia.org
$GOOGLE3 www.google.ca
$GOOGLE2        www.google.com        
$GOOGLE3        plus.google.com        
$GOOGLE        lh4.googleusercontent.com        
$IMGFST imgfast.dmzj.com
$IMGFSTD imgfastd.dmzj.com
0.0.0.0 www.googleadservices.com ##
0.0.0.0 twitter.com
0.0.0.0 csi.gstatic.com
0.0.0.0 maps.gstatic.com
0.0.0.0 ad.doubleclick.net ##
0.0.0.0 *gstatic.com
0.0.0.0 plusone.google.com ##
$GOOGLE inputtools.google.com
$GTHB github.com
$RWGTHB raw.github.com
$FCBK www.facebook.com
#ads-178
0.0.0.0 t.178.com
0.0.0.0 acg.178.com
0.0.0.0 img3.178.com
0.0.0.0 img1.178.com
0.0.0.0 img4.178.com
0.0.0.0 img0.178.com
0.0.0.0 img2.178.com
$MINUS yzh123.minus.com
$OHLOH www.ohloh.net
$MINUS minus.com
$GOOGLE www.youtube.com
$WIKIMJR manjaro.org 
$WIKIMJR wiki.manjaro.org
#99manga-ads-baidu
0.0.0.0 cpro.baidu.com
0.0.0.0 drmcmm.baidu.com
#ads-hentaistigma
0.0.0.0 ads.adxpansion.com
0.0.0.0 cdn1.ads.contentabc.com
0.0.0.0  
$CSHRZFB cashier.alipay.com
$AUTHZFB auth.alipay.com
#ads-groovshark
0.0.0.0 lessthanjake.limitedrun.com/
$ARCHWIKI wiki.archlinux.org
#google
$GOOGLE        0-focus-opensocial.googleusercontent.com        
$GOOGLE        3hdrrlnlknhi77nrmsjnjr152ueo3soc-a-calendar-opensocial.googleusercontent.com        
$GOOGLE        accounts.google.com        
$GOOGLE        zoujichunblog.appspot.com        
$GOOGLE        ajax.googleapis.com        
$GOOGLE        android.l.google.com        
$GOOGLE        a-oz-opensocial.googleusercontent.com        
$GOOGLE        apis.google.com        
$GOOGLE        appengine.google.com        
$GOOGLE        bks0.books.google.com        
$GOOGLE        bks1.books.google.com        
$GOOGLE        bks2.books.google.com        
$GOOGLE        bks3.books.google.com        
$GOOGLE        bks4.books.google.com        
$GOOGLE        bks5.books.google.com        
$GOOGLE        bks6.books.google.com        
$GOOGLE        bks7.books.google.com        
$GOOGLE        bks8.books.google.com        
$GOOGLE        bks9.books.google.com        
$GOOGLE        blogsearch.google.cn        
$GOOGLE        blogsearch.google.com.hk        
$GOOGLE        books.google.com        
$GOOGLE        browserchannel-docs.l.google.com        
$GOOGLE        browserchannel-spreadsheets.l.google.com        
$GOOGLE        browsersync.google.com        
$GOOGLE        cache.pack.google.com        
$GOOGLE        calendar.google.com        
$GOOGLE        chatenabled.mail.google.com        
$GOOGLE        checkout.google.com        
$GOOGLE        chrome.google.com        
$GOOGLE        clients1.google.com        
$GOOGLE        clients1.googleusercontent.com        
$GOOGLE        clients2.google.com        
$GOOGLE        clients2.googleusercontent.com        
$GOOGLE        clients3.google.com        
$GOOGLE        clients3.googleusercontent.com        
$GOOGLE        clients4.google.com        
$GOOGLE        clients4.googleusercontent.com        
$GOOGLE        clients5.google.com        
$GOOGLE        clients5.googleusercontent.com        
$GOOGLE        clients6.google.com        
$GOOGLE        clients6.googleusercontent.com        
$GOOGLE        clients7.google.com        
$GOOGLE        clients7.googleusercontent.com        
$GOOGLE        code.google.com        
$GOOGLE        csi.gstatic.com        
$GOOGLE        desktop.google.com        
$GOOGLE        desktop2.google.com        
$GOOGLE        ditu.google.cn        
$GOOGLE        ditu.google.com        
$GOOGLE        dl.google.com        
$GOOGLE        docs.google.com        
$GOOGLE        earth.google.com        
$GOOGLE3        encrypted.google.com        
$GOOGLE        encrypted.google.com.hk        
$GOOGLE        encrypted-tbn0.google.com        
$GOOGLE        encrypted-tbn1.google.com        
$GOOGLE        encrypted-tbn2.google.com        
$GOOGLE        encrypted-tbn3.google.com        
$GOOGLE        feedback.googleusercontent.com        
$GOOGLE        finance.google.com        
$GOOGLE        fonts.googleapis.com        
$GOOGLE        g0.gstatic.com        
$GOOGLE        gg.google.com        
$GOOGLE        ghs.google.com        
$GOOGLE        ghs.l.google.com        
$GOOGLE        google.com        
$GOOGLE        google.com.hk        
$GOOGLE        googlecl.googlecode.com        
$GOOGLE        googlehosted.l.googleusercontent.com        
$GOOGLE        groups.google.com        
$GOOGLE        id.google.cn        
$GOOGLE        id.google.com        
$GOOGLE        id.google.com.hk        
$GOOGLE        images.google.com        
$GOOGLE        images.google.com.hk        
$GOOGLE        images0-focus-opensocial.googleusercontent.com        
$GOOGLE        images1-focus-opensocial.googleusercontent.com        
$GOOGLE        images2-focus-opensocial.googleusercontent.com        
$GOOGLE        images3-focus-opensocial.googleusercontent.com        
$GOOGLE        images4-focus-opensocial.googleusercontent.com        
$GOOGLE        images5-focus-opensocial.googleusercontent.com        
$GOOGLE        images6-focus-opensocial.googleusercontent.com        
$GOOGLE        images-lso-opensocial.googleusercontent.com        
$GOOGLE        images-oz-opensocial.googleusercontent.com        
$GOOGLE        images-pos-opensocial.googleusercontent.com        
$GOOGLE        investor.google.com        
$GOOGLE        khms0.google.com        
$GOOGLE        khms1.google.com        
$GOOGLE        labs.google.com        
$GOOGLE        large-uploads.l.google.com        
$GOOGLE        lh1.ggpht.com        
$GOOGLE        lh1.googleusercontent.com        
$GOOGLE        lh2.ggpht.com        
$GOOGLE        lh2.googleusercontent.com        
$GOOGLE        lh3.ggpht.com        
$GOOGLE        lh3.googleusercontent.com        
$GOOGLE        lh4.ggpht.com        
$GOOGLE        lh5.ggpht.com        
$GOOGLE        lh5.googleusercontent.com        
$GOOGLE        lh6.ggpht.com        
$GOOGLE        lh6.googleusercontent.com        
$GOOGLE        m.google.com        
$GOOGLE        mail.google.com        
$GOOGLE        mail-attachment.googleusercontent.com        
$GOOGLE        maps.google.cn        
$GOOGLE        maps.google.com        
$GOOGLE        maps.gstatic.cn        
$GOOGLE        maps.gstatic.com        
$GOOGLE        maps-api-ssl.google.com        
$GOOGLE        mt0.google.cn        
$GOOGLE        mt0.google.com        
$GOOGLE        mt1.google.cn        
$GOOGLE        mt1.google.com        
$GOOGLE        mt2.google.cn        
$GOOGLE        mt2.google.com        
$GOOGLE        mt3.google.cn        
$GOOGLE        mt3.google.com        
$GOOGLE        mts0.google.com        
$GOOGLE        mts1.google.com        
$GOOGLE        music.google.com        
$GOOGLE        music.googleusercontent.com        
$GOOGLE        music-streaming.l.google.com        
$GOOGLE        mw2.google.com        
$GOOGLE        news.google.cn        
$GOOGLE        news.google.com        
$GOOGLE        news.google.com.hk        
$GOOGLE        newsfeed-dot-latest-dot-rovio-ad-engine.appspot.com        
$GOOGLE        nt0.ggpht.com        
$GOOGLE        nt1.ggpht.com        
$GOOGLE        nt2.ggpht.com        
$GOOGLE        nt3.ggpht.com        
$GOOGLE        oauth.googleusercontent.com        
$GOOGLE        ode25pfjgmvpquh3b1oqo31ti5ibg5fr-a-calendar-opensocial.googleusercontent.com        
$GOOGLE        pack.google.cn        
$GOOGLE        pack.google.com        
$GOOGLE        picasa.google.com        
$GOOGLE        picasaweb.google.com        
$GOOGLE        picasaweb.google.com.hk        
$GOOGLE        places.google.com        
$GOOGLE        plus.google.com.hk        
$GOOGLE        pop.gmail.com        
$GOOGLE        profiles.google.com        
$GOOGLE        project-slingshot-gp.appspot.com        
$GOOGLE        s1.googleusercontent.com        
$GOOGLE        s2.googleusercontent.com        
$GOOGLE        s3.googleusercontent.com        
$GOOGLE        s4.googleusercontent.com        
$GOOGLE        s5.googleusercontent.com        
$GOOGLE        s6.googleusercontent.com        
$GOOGLE        safebrowsing.clients.google.com        
$GOOGLE        safebrowsing-cache.google.com        
$GOOGLE        sandbox.google.com        
$GOOGLE        scholar.google.cn        
$GOOGLE        scholar.google.com        
$GOOGLE        scholar.google.com.hk        
$GOOGLE        scholar.l.google.com        
$GOOGLE        services.google.com        
$GOOGLE        sites.google.com        
$GOOGLE        sketchup.google.com        
$GOOGLE        spreadsheets.google.com        
$GOOGLE        ssl.google-analytics.com        
$GOOGLE        ssl.gstatic.com        
$GOOGLE        suggestqueries.google.com        
$GOOGLE        t.doc-0-0-sj.sj.googleusercontent.com        
$GOOGLE        t0.gstatic.com        
$GOOGLE        t1.gstatic.com        
$GOOGLE        t2.gstatic.com        
$GOOGLE        t3.gstatic.com        
$GOOGLE        talkgadget.google.com        
$GOOGLE        talkx.l.google.com        
$GOOGLE        themes.googleusercontent.com        
$GOOGLE        toolbar.google.com        
$GOOGLE        toolbar.google.com.hk        
$GOOGLE        toolbarqueries.clients.google.com        
$GOOGLE        toolbarqueries.google.com.hk        
$GOOGLE        tools.google.com        
$GOOGLE        translate.google.cn        
$GOOGLE        translate.google.com.hk        
$GOOGLE        translate.googleapis.com        
$GOOGLE        uploadsj.clients.google.com        
$GOOGLE        v8mq9slfbk1dglresapkg0i5f8pm64lc-a-calendar-opensocial.googleusercontent.com        
$GOOGLE        video.google.cn        
$GOOGLE        video.google.com        
$GOOGLE        video.google.com.hk        
$GOOGLE        voice.google.com        
$GOOGLE        wave.google.com        
$GOOGLE        webcache.googleusercontent.com        
$GOOGLE        wenda.google.com.hk        
$GOOGLE        www.gmail.com        
$GOOGLE        www.google.com.hk        
$GOOGLE        www.google-analytics.com        
$GOOGLE        www.googleapis.com        
$GOOGLE        www.googlelabs.com        
$GOOGLE        www.gstatic.com        
$GOOGLE        www-calendar-opensocial.googleusercontent.com        
$GOOGLE        www-opensocial.googleusercontent.com        
$GOOGLE        www-oz-opensocial.googleusercontent.com        
$GOOGLE        r3270-dot-latest-dot-project-slingshot-gp.appspot.com        
$GOOGLE        bt26mravu2qpe56n8gnmjnpv2inl84bf-a-oz-opensocial.googleusercontent.com        
$GOOGLE        rbjhe237k979f79d87gmenp3gejfonu9-a-oz-opensocial.googleusercontent.com        
$GOOGLE        k6v18tjr24doa89b55o3na41kn4v73eb-a-oz-opensocial.googleusercontent.com        
$GOOGLE        8kubpeu8314p2efdd7jlv09an9i2ljdo-a-oz-opensocial.googleusercontent.com        
$GOOGLE        adstvca8k2ooaknjjmv89j22n9t676ve-a-oz-opensocial.googleusercontent.com        
$GOOGLE        ob7f2qc0i50kbjnc81vkhgmb5hsv7a8l-a-oz-opensocial.googleusercontent.com        
$GOOGLE        53rd6p0catml6vat6qra84rs0del836d-a-oz-opensocial.googleusercontent.com        
$GOOGLE        u807isd5egseeabjccgcns005p2miucq-a-oz-opensocial.googleusercontent.com        
$GOOGLE        r70rmsn4s0rhk6cehcbbcbfbs31pu0va-a-oz-opensocial.googleusercontent.com        
$GOOGLE        59cbv4l9s05pbaks9v77vc3mengeqors-a-oz-opensocial.googleusercontent.com        
$GOOGLE        i8brh95qor6r54nkl52hidj2ggcs4jgm-a-oz-opensocial.googleusercontent.com        
$GOOGLE        upt14k1i2veesusrda9nfotcrbp9d7p5-a-oz-opensocial.googleusercontent.com        
$GOOGLE        debh8vg7vd93bco3prdajidmm7dhql3f-a-oz-opensocial.googleusercontent.com        
$GOOGLE        4fjvqid3r3oq66t548clrdj52df15coc-a-oz-opensocial.googleusercontent.com        
$GOOGLE        hsco54a20sh11q9jkmb51ad2n3hmkmrg-a-oz-opensocial.googleusercontent.com        
$GOOGLE        qhie5b8u979rnch1q0hqbrmbkn9estf7-a-oz-opensocial.googleusercontent.com        
$GOOGLE        e6ha3snmi09c57cs4h4dnoa006cgfjfu-a-oz-opensocial.googleusercontent.com        
$GOOGLE        66fl6oqbdsqf5fjl032t5iulimtqjhpa-a-oz-opensocial.googleusercontent.com        
$GOOGLE        vvpk2b7flnbhcm2p10u4hcnatnp40i3i-a-oz-opensocial.googleusercontent.com        
$GOOGLE        0rgn8o7pqk7dq7rm8q0639erjd8gnf7g-a-oz-opensocial.googleusercontent.com        
$GOOGLE        cfmmurgvo3fqrmfu0tjfcpgdt7mh6ccv-a-oz-opensocial.googleusercontent.com        
#twitter
$TWITTER oauth.twitter.com        
$TWITTER twitter.com        
$TWITTER www.twitter.com        
$TWITTER mobile.twitter.com        
$TWITTER api.twitter.com        
$TWITTER search.twitter.com        
$TWITTER userstream.twitter.com        
$TWITTER ssl.twitter.com        
$TWITTER status.twitter.com        
$TWITTER assets0.twitter.com        
$TWITTER assets1.twitter.com        
$TWITTER assets2.twitter.com        
$TWITTER assets3.twitter.com        
$TWITTER static.twitter.com        
$TWITTER platform.twitter.com        
$TWITTER platform0.twitter.com        
$TWITTER help.twitter.com        
$TWITTER support.twitter.com        
$TWITTER si0.twimg.com        
$TWITTER si1.twimg.com        
$TWITTER si2.twimg.com        
$TWITTER si3.twimg.com        
$TWITTER si4.twimg.com        
$TWITTER si5.twimg.com        
$TWITTER upload.twitter.com
$TWITTER t.co
$COMIC178 www.dmzj.com
$GOOGLE drive.google.com
$GOOGLE docs.google.com
$GOOGLE www.blogger.com
$GOOGLE developers.google.com
$WIKI en.wikipedia.org
$HENTAI hentaischool.com
$TOPHENTAI hentai.animestigma.com
$XMARKS my.xmarks.com
$XMARKS login.xmarks.com
$TAOBAO www.taobao.com
$LGTAOBAO login.taobao.com
$STAOBAO s.taobao.com
$EHENTAI g.e-hentai.org
$YZH www.jottit.com
$YZH yzh.jottit.com
$ITMTAOBAO item.taobao.com
$TMLTAOBAO detail.tmall.com
$BAIDU www.baidu.com
$ZHIDAO zhidao.baidu.com
$BAIKE baike.baidu.com
$ZHWIKI zh.wikipedia.org
$MJR repo.manjaro.org.uk
#ads
0.0.0.0 ads.juicyads.com #e-hentai
0.0.0.0 static.exoclick.com #tophentai
0.0.0.0 media.hw.adxpansion.com #tophentai
0.0.0.0 market.178.com #178manga
127.0.0.1 pic1.178.com
127.0.0.1 img.178.com
127.0.0.1 www.jiqing321.com
127.0.0.1 freefuckfind.com
0.0.0.0 content.aimatch.com
0.0.0.0 redirect.ero-advertising.com
0.0.0.0 www.pornwave.com
0.0.0.0 simg.sinajs.cn
0.0.0.0 img5.178.com
$TRANS translate.google.com 
$SSL encrypted.google.com
$GOOGLE feeds.feedburner.com
$MJRCN mirrors.ustc.edu.cn
$AUR aur.archlinux.org
$ETHERPAD notes.typo3.org
$HJTT hentai.jottit.com
#end_update_hosts
#windows 7 C:\Windows\System32\drivers\etc\hosts
#manjaro /etc/hosts
EOF
